CREATE TABLE user_activity_log (
	log_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '日志ID',
	user_id INT NOT NULL COMMENT '用户ID',
	activity_description VARCHAR(255) NOT NULL COMMENT '活动描述',
	activity_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '活动时间',
	create_by INT COMMENT '创建人',
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_by INT COMMENT '修改人',
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '用户操作日志表';