CREATE TABLE user_login (
	login_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '登录记录ID',
	user_id INT NOT NULL COMMENT '用户ID',
	login_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
	logout_time DATETIME COMMENT '登出时间',
	create_by INT COMMENT '创建人',
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_by INT COMMENT '修改人',
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '用户登录记录表';